output_folder:  output_pangenome_variations_pandora_paper_tag1
samples:        metadata/samples.pandora_paper_tag1.csv
flank_length:   50
varifier_image: docker://leandroishilima/varifier:pandora_paper_tag1